# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Example add-on
version: "1.1.0"
slug: example
description: Example add-on
url: "https://github.com/habuild/sbfspot_addon/tree/main/example"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
init: false
options:
  message: "Hello world..."
schema:
  message: "str?"
image: "ghcr.io/habuild/{arch}-addon-example"
