# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: SBFspot
version: "2022.3.0"
slug: sbfspot
description: SBFspot add-on for Home Assistant
url: "https://github.com/habuild/sbfspot_addon/tree/main/sbfspot"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
options:
  message: "Hello world...sbfspot"
schema:
  message: "str?"
image: "ghcr.io/sbfspot_addon/{arch}-addon-example"
